use_frameworks!

platform :ios, '13.4'
source 'https://github.com/TedoooTeam/tedooo-pod-repo.git'
source 'https://cdn.cocoapods.org/'

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end
